import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { id, title, description, severity, score, category, ownerName, mitigationPlan, contingencyPlan } = body;

    const jiraIssuePayload = {
      fields: {
        project: { key: 'MNB' },
        summary: `[RISK ${id}] ${title}`,
        description: `*Risk Category:* ${category}\n*Severity:* ${severity} (Score: ${score}/25)\n*Assigned Owner:* ${ownerName}\n\n*Description:*\n${description}\n\n*Mitigation Strategy:*\n${mitigationPlan}\n\n*Contingency Plan:*\n${contingencyPlan}`,
        issuetype: { name: 'Bug' },
        priority: { name: severity === 'Critical' ? 'Highest' : severity === 'High' ? 'High' : 'Medium' }
      }
    };

    const githubIssueMarkdown = `## 🚨 [${id}] ${title}
**Category:** \`${category}\` | **Severity:** \`${severity}\` (Score: ${score}/25)  
**Assigned Owner:** ${ownerName}

### 📝 Description
${description}

### 🛡️ Mitigation Strategy
${mitigationPlan}

### ⚠️ Contingency Plan
${contingencyPlan}

---
*Generated by MNB Research Risk Register Copilot*
`;

    return NextResponse.json({
      success: true,
      jiraPayload: jiraIssuePayload,
      githubMarkdown: githubIssueMarkdown,
      githubNewIssueUrl: `https://github.com/itzdevilsunny/risk-register-copilot/issues/new?title=${encodeURIComponent(`[${id}] ${title}`)}&body=${encodeURIComponent(githubIssueMarkdown)}`
    });

  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
