import { NextResponse } from 'next/server';
import { getRiskById, logAuditEvent } from '@/lib/server/db';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const riskId = body.riskId || body.id;
    const existingRisk = riskId ? getRiskById(riskId) : null;

    const id = riskId || existingRisk?.id || 'RSK-CUSTOM';
    const title = body.title || existingRisk?.title || body.payload?.fields?.summary || 'Operational Risk Assessment';
    const description = body.description || existingRisk?.description || 'Operational risk threat under governance oversight.';
    const severity = body.severity || existingRisk?.severity || 'High';
    const score = body.score || existingRisk?.score || 12;
    const category = body.category || existingRisk?.category || 'Technical';
    const ownerName = body.ownerName || existingRisk?.ownerName || 'Sunny Prasad';
    const mitigationPlan = body.mitigationPlan || existingRisk?.mitigationPlan || 'Implement preventative controls and SLA monitoring.';
    const contingencyPlan = body.contingencyPlan || existingRisk?.contingencyPlan || 'Activate disaster recovery contingency window.';

    const jiraIssuePayload = body.payload || {
      fields: {
        project: { key: 'MNB' },
        summary: `[${id}] ${title}`,
        description: `*Risk Category:* ${category}\n*Severity:* ${severity} (Score: ${score}/25)\n*Assigned Owner:* ${ownerName}\n\n*Description:*\n${description}\n\n*Mitigation Strategy:*\n${mitigationPlan}\n\n*Contingency Plan:*\n${contingencyPlan}`,
        issuetype: { name: severity === 'Critical' ? 'Bug' : 'Task' },
        priority: { name: severity === 'Critical' ? 'Highest' : severity === 'High' ? 'High' : 'Medium' },
        labels: ['risk-register-copilot', category.toLowerCase(), severity.toLowerCase()]
      }
    };

    const githubIssueMarkdown = `## 🚨 [${id}] ${title}
**Category:** \`${category}\` | **Severity:** \`${severity}\` (Score: ${score}/25)  
**Assigned Owner:** ${ownerName}

### 📝 Description
${description}

### 🛡️ Mitigation Strategy
${mitigationPlan}

### ⚠️ Contingency Plan
${contingencyPlan}

---
*Generated by MNB Research Risk Register Copilot*
`;

    // Generate Issue Key
    const issueNum = Math.abs(id.split('').reduce((acc: number, char: string) => acc + char.charCodeAt(0), 100)) % 900 + 100;
    const issueKey = `MNB-${issueNum}`;

    // Log to Immutable Audit Trail
    try {
      logAuditEvent({
        riskId: id,
        actionType: 'UPDATE',
        actorName: ownerName,
        actorRole: 'Risk Lead',
        changesSummary: `Exported risk item ${id} to External Issue Tracker (Jira payload generated / GitHub Ticket: ${issueKey}).`
      });
    } catch {}

    return NextResponse.json({
      success: true,
      issueKey,
      jiraPayload: jiraIssuePayload,
      githubMarkdown: githubIssueMarkdown,
      githubNewIssueUrl: `https://github.com/itzdevilsunny/risk-register-copilot/issues/new?title=${encodeURIComponent(`[${id}] ${title}`)}&body=${encodeURIComponent(githubIssueMarkdown)}`,
      message: `Issue tracker integration payload synthesized successfully for ${id}.`
    });

  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
